### ISSUE TITLE
rmtp with authentication

### ISSUE THREAD

**Issue by jrichardsz** [jkuri/ffmpeg-webcam-rtmp-stream#1]
I was able to use your application with the default rtmp which don't have authentication. Thanks for that!!! :)

My question is: How use the [streamkey](https://help.livestream.com/hc/en-us/articles/360002069647-Finding-the-RTMP-URL-and-Stream-Key-for-My-Event) at the moment of launching?

```
docker run --device /dev/video0 -it ffmpeg-webcam-rtmp-stream stream /dev/video0 rtmp://localhost/live/stream flv 1280 720 30
```

I'm using this [rtmp](https://owncast.online/docs/building/) server:

![image](https://user-images.githubusercontent.com/3322836/134048010-81c2f91d-9e2b-4f3f-bbb9-9e859d41154a.png)

Thanks

**Comment by jkuri** [comment]
I think you can provide stream key in url, i.e. `rtmp://localhost/live/{streamkey}`.
