### ISSUE TITLE
CAN'T STREAM  ON HIGHER RESOLUTIONS(WINDOWS 10)

### ISSUE THREAD

**Issue by batuhannzorlu** [jkuri/ffmpeg-webcam-rtmp-stream#2]
Hi,
I have built the project on windows10(x64), using prebuilt ffmpeg libraries. Project is woking smoothly, but the problem is i can not get higher resolutions than 800x600,(it works with lower resolutions). Application does not return anything to debug.
![pic](https://user-images.githubusercontent.com/37422935/182426719-df19d2ac-d9fd-458d-a464-e31cea7dd647.PNG)
.

**Comment by jkuri** [comment]
Hi,

try uncommenting [this](https://github.com/jkuri/ffmpeg-webcam-rtmp-stream/blob/master/src/stream.c#L177) and [that](https://github.com/jkuri/ffmpeg-webcam-rtmp-stream/blob/master/src/stream.c#L69) lines. I think you should get some more information.

**Comment by batuhannzorlu** [comment]
Hello,i should have opened the issue in C++, Sorry about that. I am moving it to C++.

**Comment by jkuri** [comment]
okay, then I am closing this.
