### ISSUE TITLE
Connection to tcp://localhost:1935 failed: Connection refused

### ISSUE THREAD

**Issue by shaunVorster** [jkuri/ffmpeg-webcam-rtmp-stream#4]
Good day.

I am trying to start up this container to test my rtmp server but i am seeing the following message when starting the container.
I have already checked the port to make sure that there is nothing else running on it and opened the tcp port on my firewall.

Any help would be greatly appreciated.

Kind regards 
Shaun 

Full docker log output:
===============
video4linux2,v4l2 @ 0x5c4dc4148a40] The V4L2 driver changed the video from 1280x720 to 640x480
- [tcp @ 0x5c4dc4150180] Connection to tcp://localhost:1935 failed: Connection refused
- [rtmp @ 0x5c4dc414fa80] Cannot open connection tcp://localhost:1935

could not open IO context!
[libx264 @ 0x5c4dc4151600] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5c4dc4151600] profile High, level 3.1, 4:2:0, 8-bit
[libx264 @ 0x5c4dc4151600] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=1 deblock=1:0:0 analyse=0x3:0x3 me=dia subme=1 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=4 lookahead_threads=4 sliced_threads=1 slices=4 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=1 keyint=12 keyint_min=1 scenecut=40 intra_refresh=0 rc=crf mbtree=0 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00

**Comment by jkuri** [comment]
hi @shaunVorster, you need to have rtmp server running so you can publish the stream to it, you can use;
```sh
docker run -it -p 1935:1935 -p 8080:8080 --name rtmp-server jkuri/urtmp
```
and then try again.

**Comment by shaunVorster** [comment]
Good day, i had the rtmp server running,
Still got the same error message. 
the server never registered any streams.

**Comment by jkuri** [comment]
if you are trying to publish stream from docker container make sure the host is accessible, use local container port or run container user `--net=host`

**Comment by shaunVorster** [comment]
I will follow up and try again in a bit.
Thanks very much. i think that may be it.

I will get back to you

**Comment by shaunVorster** [comment]
Hi. sorry for the late response. 
Running the stream container with --network host sorted the issue out. Thanks very much
